### ISSUE TITLE
RedisClientType hard to use with createClient

### ISSUE THREAD

**Issue by tobiasdiez** [redis/node-redis#1865]
The RedisClientType has two generic parameters that make it hard to use to signify the return type of `createClient`. In particular, the first argument `modules` in the declaration of `createClient` is a local variable that is not exported and thus cannot be easily reused in one's own code.

Maybe it's already enough to provide sufficiently general defaults for the generic arguments. If I'm not mistaken these parameters control more the configuration of the client and don't really influence the typing of the "normal" methods; so they are not that important for an user of a factory method.

Below is a similar observation from #1673.

---

The `RedisClientType` exported since 4.0.1 still does not work for me. Could not figure out how to make the exported `RedisClientType`, `RedisClientOptions` and the type returned by `createClient` compatible. Here is an [example that illustrates the issue](https://codesandbox.io/s/node-redis-typescript-fhzck).

The following does not compile unless someone knows how to type `RedisClientOptions` correctly (refer to the code sandbox link above).

```
import { createClient, RedisClientOptions, RedisClientType } from "redis";

const factory = (options: RedisClientOptions<any, any>): RedisClientType => {
  return createClient(options);
};

const client: RedisClientType = factory({...});
```

Instead, I am doing this for now:

```
import { createClient} from "redis";
type RedisClientType = ReturnType<typeof createClient>;
type RedisClientOptions = Parameters<typeof createClient>[0];

const factory = (options: RedisClientOptions): RedisClientType => {
  return createClient(options);
};

const client: RedisClientType = factory({...});
```

_Originally posted by @tbinna in https://github.com/redis/node-redis/issues/1673#issuecomment-993335708_

**Comment by leibale** [comment]
`RedisModules` extends the client with the installed modules commands, `RedisScripts` extends it with the defined lua scripts ([see here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQYQDbBoB2MANHACZoBmwRaAyqsGPAL5zVQQhwDkAASIQqAWnQVgAZwD0yAsRh8A3AFgAUBuQQiU+CBEBXPGin5CJOAF4U6LLgUkAFAg1x3cAxWOmAXIjcPIK8ff1d1IMiPbRAQDCIKMMColLgYKHipamgQAEEoAHNDEEUpJz0ofwq6AvIiYv96kAAjNCgASgCI1J73dBhDKCI4AG0+AFkAeQARAFUAGQBRADocSfHx3IA5ab5yCrri5ZgIBnSap3aAXTVu3qC2UmT793TM7KgQACU0MDwATyc6D+-yq5yIBXajWKrSgXReqX6g2GWxhbSBvwB7VuCI8bGeqXxd0iRIeGjY2I0Ghg-zAaBQPDiCXyRRKJCk1jgAAUMBkStgoFIADw0ukQaieIwmMyOGDLEImZYxJkUAB8txkMg8AD0APxU9Si+nK+IUH4gzk-AZDAAqtLQIvt4sl3ml5kU8qlaCVjNN6o0mp1+s06m0ungUmYrBlFngNlQmGw7uc4SCkagLBgUiSxLTUZg-iotHoTAzrBcBJSDBwXwAklybf4+EihnAAEQARjbe0rUS2s3GACFFl8APqTABio4A0osAJoMfwABieuZSb10HzyhWKpXK6TBGYhhxA0JabU6qdxcBbwxGBzgTWOp3BBUuN17JNXLw3WRy5oBDEQUPGooUfNE4SvXFbzgVFzygICsRxe5SRSClniJClbmpe04HTTMWV3dlOR5Pk0AFYUjWdfDo2TOUaJgf11EDdw9QNI08PzAD-ktcjkTtOlHTFCUGJjD0GKYli4D1IA)).

In case you want to ignore modules and scripts, `Record<string, never>` should do the trick:
```
RedisClientType<Record<string, never>, Record<string, never>>
```

**Comment by tobiasdiez** [comment]
Thanks! Would it then be an idea to set these generic parameters to `Record<string, never>` by default, i.e. `RedisClientType` without any generics specified is equivalent to what you wrote above?

**Comment by restfulhead** [comment]
@leibale Could you provide an example how to use a typed client with scripts?

What works for me without defining scripts:

```
export type RedisClientType = ReturnType<typeof createClient>

myCreateClient(port, host, pw): RedisClientType {
 const client: RedisClientType = createClient({
      socket: { port, host, tls: true },
      password: pw,
    })
  return client
}
```

However, once I add a script, I get a types are incompatible error.

```
myCreateClient(port, host, pw): RedisClientType {
 const client: RedisClientType = createClient({
      socket: { port, host, tls: true },
      password: pw,
      scripts: {
        add: defineScript({
          NUMBER_OF_KEYS: 1,
          SCRIPT: 'local val = redis.pcall("GET", KEYS[1]);' + 'return val + ARGV[1];',
          transformArguments(key: string, toAdd: number): string[] {
            return [key, toAdd.toString()]
          },
          transformReply(reply: number): number {
            return reply
          },
        }),
      },
    })
  return client
}
```

**Comment by leibale** [comment]
@restfulhead 

```typescript
import { createClient, defineScript, RedisModules, RedisScripts, RedisClientType } from '@node-redis/client';

interface ClientOptions<
    M extends RedisModules,
    S extends RedisScripts
> {
    port: number;
    host: string;
    pw: string;
    modules?: M;
    scripts?: S;
}

function clientFactory<
    M extends RedisModules,
    S extends RedisScripts
>(options: ClientOptions<M, S>): RedisClientType<M, S> {
    return createClient({
        socket: {
            port: options.port,
            host: options.host
        },
        password: options.pw,
        modules: options.modules,
        scripts: options.scripts
    });
}

const client = clientFactory({
    port: 6379,
    host: 'host',
    pw: 'pw',
    scripts: {
        add: defineScript({
          NUMBER_OF_KEYS: 1,
          SCRIPT: 'local val = redis.pcall("GET", KEYS[1]);' + 'return val + ARGV[1];',
          transformArguments(key: string, toAdd: number): Array<string> {
            return [key, toAdd.toString()]
          },
          transformReply(reply: number): number {
            return reply
          },
        })
    }
});

client.add('key', 1);
//     ^?
```

[playground](https://www.typescriptlang.org/play?ssl=37&ssc=72&pln=37&pc=59#code/JYWwDg9gTgLgBAbzgYygUwIYzQYQDbBoB2MANHACZoBmwRaAyqsGGXAEpoXADOAshAoBXPGh7lO3HkygsY4jl175CJACoBPMGjgBfONSgQQcAOQABIoLQBadFID0yAsRimA3AFgAUD7rYoagxkHRVXAHlWYAgiHgAeHzgkuD44NAAPbCIKHkUpAWFRcUTkhjTM4hy83hk5Hh8APkQSpMhYAC44IiEQACM0KC9vZLgACwgeGE7J2SIAcyGRsAB3aZhZhZa4EEERMQB+Tr5F5J5mVh5DuAYh3R8faiEiZBhoohQXEgAxYJhoDQSw2SqQyWSqkl4BT2xSBSTKoMquQh0nO8kaAAoIFEYjxOmESJFXji4nxyAwGgBKTrI-EwTTaElkpoILboGBCKDvVCYbC09Es2EjOA8CDIADWaCmzUFQuSbSlWKJsQAdPLSFtZUlxpNOoq3jxldqYBrkrp1TK5RgeDxltAKLrsSqVubNdtdkUHUqDTtCmIXZqzrILp79crA3UtroKbd7t5kDj4M5VPAALwfZM-F7-flbeWdABsAGYAOwATn9WomUtMRtMFbgK06phWda24eD0tdGAo9soNDojFROYtIwAcgBVPgAIQAouwAPrhL7zgDSM4AmgxOgBGeuyhg4dgASQACmom3hRRg8HAAG7XuBp+y8VXIa94dEAIgA4jO1J-yDXTcAG1twAXWjUw4AAajMNkOXee8b1ggBBdhvwANVAsD3FbEdknWDBYmoaAQBQqA5h6VweHRCUNDWDZyD+FCe06bo+gGKk4HIqAMABGY6DmZkTVleDOTgYC6KYiAWIoZU-gYdZBPRCkwJE009yFQjiNIzgwDwDR0XQfT6K6Hp+igLj2IsztXWSMT3mMgz1KSM11KjSMfCjIYfCTVxlW7Ch0VMOi6zgbdox8BwHCFAA9fYgA)

**Comment by restfulhead** [comment]
Hm...thanks for the example, but what I really need is a factory that returns the type of the configured client; not the generic one. My application will use the same client everywhere, so I need a type to pass around the configured client.

For example say I'd like to pass my client to a function:

```ts
// how to best define the MyClient type here?
function doAdd(client: MyClient) {
   client.add('key', 1);
}
```

Now adding on to your example, the following works, but requires a lot of declaration:

```ts
export type MyClient = RedisClientType<RedisModules, {
    add: {
        NUMBER_OF_KEYS: number;
        SCRIPT: string;
        transformArguments(this: void, key: string, toAdd: number): Array<string>;
        transformReply(this: void, reply: number): number;
    } & 
    { 
        SHA1: string;
    }
}>
```

@leibale Would it be feasible to export the RedisScript and SHA1 types?

This would make the declaration (and therefore using) this library much easier:

```
export interface ConfiguredRedisScripts extends RedisScripts {
  add: RedisScript
}
export type MyClient = RedisClientType<RedisModules, ConfiguredRedisScripts>

function doAdd(client: MyClient) {
   client.add('key', 1);
}
```

**Comment by leibale** [comment]
@restfulhead 

```javascript
import { createClient } from '@node-redis/client';

export const client = createClient({
  modules: {
    // ...
  },
  scripts: {
    // ...
  }
});

export type CustomRedisClient = typeof client;

const duplicate = client.duplicate();
```


```javascript
import { createClient } from '@node-redis/client';

const modules = {
  // ...
};

const scripts = {
  // ...
};

export type CustomRedisClient = RedisClientType<typeof modules, typeof scripts>;

export function clientFactory(): CustomRedisClient {
  return createClient({
    modules,
    scripts
  });
}
```

**Comment by tobiasdiez** [comment]
@leibale thanks for adding the defaults to the RedisClientType params. However, now the following code
```ts
import redis, { RedisClientType } from 'redis'
function createRedisClient(): Promise<RedisClientType> {
    const client = redis.createClient(...redisConfig...)
    await client.connect()
    return client
}
```
fails with an error of the type
```
error TS2322: Type 'RedisClientType<{ graph: { CONFIG_GET: typeof import("/home/runner/work/JabRefOnline/JabRefOnline/node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("/home/runner/work/JabRefOnline/JabRefOnline/node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: typeo...' is not assignable to type 'RedisClientType<Record<string, never>, Record<string, never>>'.
```

**Comment by leibale** [comment]
@tobiasdiez #1984 should fix it

**Comment by tobiasdiez** [comment]
Thanks! I haven't had a chance to try it, but codewise it looks good to me.

**Comment by tobiasdiez** [comment]
I hate to bother you again, but the code from above (https://github.com/redis/node-redis/issues/1865#issuecomment-1038249865) is still not working and now fails with
```
Type 'import("file:///node_modules/@node-redis/client/dist/lib/client/index").RedisClientType<{ graph: { CONFIG_GET: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: typeo...' is not assignable to type 'import("file:///node_modules/redis/dist/index").RedisClientType<{ graph: { CONFIG_GET: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: typeof import("file:///node_m...'.
  Type 'RedisClientType<{ graph: { CONFIG_GET: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: typeof import("file:///node_modules/@node-redis/graph/dist/commands/SLOWLOG")...' is not assignable to type 'RedisClient<{ graph: { CONFIG_GET: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: typeof import("file:///node_modules/@node-redis/graph/dist/commands/SLOWLOG"); };...'.
    Types of property 'options' are incompatible.
      Type 'import("file:///node_modules/@node-redis/client/dist/lib/client/index").RedisClientOptions<{ graph: { CONFIG_GET: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: ty...' is not assignable to type 'import("file:///node_modules/@node-redis/client/dist/lib/client/index").RedisClientOptions<{ graph: { CONFIG_GET: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: ty...'. Two different types with this name exist, but they are unrelated.
        Type 'import("file:///node_modules/@node-redis/client/dist/lib/client/index").RedisClientOptions<{ graph: { CONFIG_GET: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: ty...' is not assignable to type 'import("file:///node_modules/@node-redis/client/dist/lib/client/index").RedisClientOptions<{ graph: { CONFIG_GET: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("file:///node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: ty...'. Two different types with this name exist, but they are unrelated.
          Type 'RedisScripts' is not assignable to type 'Record<string, never>'.
            'string' index signatures are incompatible.
              Type 'RedisScript' is not assignable to type 'never'.(2322)
```
See https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBFApgE2AZwDRwN5wEoroDCANsIgHYwAqAnmInAL5wBmUEIcA5EqmtwBQAQzS0KAYzYBXSTGAQKcCUmExEBfqXJUAFAEoAXHAAKHEOkQAeTcTKUa9RAD4cguB+WK08CfapwALwIhGgAdCqIaojaDgbunjBOyv6ODEFwSQwQrCk6MAkeWYwA4ogwAMoqwGBp1kRwiAAe6hTIaPihsVR0DFbCFLRYA7TOrsENza3tnVqpvdYjWMAUrIhQcNSuAPybcMayANYUEADuFADchZnJaNW1Cxlllfd1Vn75C87XAPQ-nh4AHrba7CU7CYC+VIRRQURASGDxAFIGDSKBKD4OQRMIA

The issue here is that the script type returned by `createClient` is `redis.RedisScript` but the default script type for `RedisClientType` is `Record<string, never>`. Would it be possible to change the default?

**Comment by tobiasdiez** [comment]
@leibale can this issue please be reopened, it is still not working as reported above https://github.com/redis/node-redis/issues/1865#issuecomment-1075030395. Thanks!

**Comment by leibale** [comment]
@tobiasdiez the default is that there are no scripts, why is that a problem?

**Comment by tobiasdiez** [comment]
The issue is that if you do use scripts, then you need to specify the type of the scripts everywhere. Instead of "no scripts", something like "generic scripts" would be helpful. The goal is to make the following code work
```
import redis, { RedisClientType } from 'redis'
function createRedisClient(): Promise<RedisClientType> {
    const client = redis.createClient(...redisConfig...)
    await client.connect()
    return client
}

function something(client: RedisClientType) {}
something(await createRedisClient())
```
Currently, one need to use `RedisClientType<any, any, any>`.

**Comment by leibale** [comment]
@tobiasdiez
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBFApgE2AZwDRwN5wEoroDCANsIgHYwAqAnmIlgamgLITICuJim+haAMoBjKMDAw+zdADFOFYTGAQKfZIgBmwCohFiJcAL5wNUCCDgByJC0sBuAFAPhKtPDSjxkuAF4cDuEC4D30YAC44dS0dPS8ACmwAoOTBIjwASQAFagjrRBhOKAo4AEE8AHEANQBtAEYAXUsMJOTAmCgAQ1UNaBASqABzThBKSTiOwYiKYYAjRCgASn9WlYR8wuLqiYGAOhgIQXbtAbiF+sdVo2bL9q60HqgQAjASWjikF9oItzEKAaXEpdkkgCkU4AA5Wbzd6IT4LC6rQwtIwLBzGDpoOAuVQwRwODG0BQmeSKZTFUAvYDCYAwU7LILYtxYsijXxrFg7USIDowRCkchUBLBTwSTGGeFOZLCFlUHYhLwIwIAeiVrQAegB+SVBDoAdw6NOZApgnJUOkUp2RyJBGyNo0cSPxaEJwmJCiUKjgA0o8ypAB5kaw4IgAB68ijITHSNgcbi8a5BGTBsOUSP8Fhyd1kzDIwTJ8Np6OxUUOAB8cQgEmzEUBQRAsZ4aA1EVYirdpNczbgMjb8tFXcEDoWEUyZhA6EQfuj-NGdAYftYWBkWEEpdL9MCjPg0uNbJs6E5SB5fJltMrHtUEuReoN29Ppoo5tpqOS1vWYJ39rRTi3dqobJvQ1vR0MRhCFPtvHFPFP1lCDHBVdUNSAA

**Comment by tobiasdiez** [comment]
Thanks but this is not really what I need. My requirements (and I believe many others are in a similar position) are as follows:
- Have a factory method in one module, that creates a redis client. (This factory method is then registered in the dependency framework)
- In other modules, I would like to use the redis client, i.e. as a constructor or method argument.

In both instances, I'm not really able to easily type the redis client. I could pass down the generics as you suggest with your `generic` function, but that is unhandy since now every other method that uses the redis client needs these generics - but in my application I only have one redis client so the generics are actually fixed. 

The following code works
```ts
import redis, { RedisClientType } from 'redis'
type RedisClient = RedisClientType<redis.RedisModules, redis.RedisFunctions, redis.RedisScripts>
async function createRedisClient(): Promise<RedisClient> {
    const client = redis.createClient()
    await client.connect()
    return client
}
```
My suggestion is that the generics of `RedisClientType` default to `<redis.RedisModules, redis.RedisFunctions, redis.RedisScripts>` so that one can use `RedisClientType` directly over `RedisClient`. 
By the way, the redis client returned by `createClient` has more modules than `redis.RedisModules`. I think `redis.RedisModules` should be the same as what `createClient` returns without any args.
Another suggestion: rename `RedisClientType` to `RedisClient`, the type suffix isn't necessary and its clear from the context that its a type.

**Comment by leibale** [comment]
1. I can't rename `RedisClientType` to `RedisClient` because:
1.1. `RedisClient` is the name of the class
1.2. It'll be a breaking change
2. `RedisModules` is just a generic type from `@redis/client`, don't confuse it with the default modules in `redis`, which I should probably export as well - wanna open an issue about it?
3. Why do you think that every method will need these generics? see [this example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBFApgE2AZwDRwN5wEoroDCANsIgHYwAqAnmIlgamgLITICuJim+haAMoBjKMDAw+zdADFOFYTGAQKfZIgBmwCohFiJcAL5wNUCCDgByJC0sBuAFAOAhmloKT8xcopwA5pSIYsIAPA5wEXCscIgAHjCUyGj8LOxcPJjhkTIx8YnJ0mhyCkoqmZFwgrkJFEkp6Hrikg4AfAAUEBI+aABcOFkRIBzcvAD8fayOFRpeparjcDJTkWiiTWgLgo6GAJR9AApmIOiIIYWk5FR0DCGsWDJYgi0t-RXCZfDCZJTwALwIAgAdKJEM4Ehcfh0umUdo4BnBnAB3ZzAT7fKjAlQ6RRtHbw+FIGCcKC+L6XGDbJwAeipcBgAAsgogEUg4BQIP5AsFkto6Yy4Jw0M4AnAIBo+cyyT8HO9VGjyXB-gEdME2th4at9JI+uqKhVNU0+uotDpGhI1fC9ZFBEQ8ABJfbUPrWRBEklwACCeAA4gA1ADaAEYALqWDCWq10qDOVQaaAgD1QPycEA-NBtZxJvoUFMAIyCO1ekeLhOJvn9mb8gJgEEEMDEFD8uODy2LEUM4bbkXrMbQcagIAIYBItDaSGHtD6aHr2j8hd1Xb1pfdADk80Ex4gJ7CI1bDLujHiKvvdnCgA)

**Comment by tobiasdiez** [comment]
1. Makes sense, okay!
2. Done: https://github.com/redis/node-redis/issues/2241
3. What I meant is that function accepting a `RedisClientType` would then need generic arguments as well, e.g.
  ```ts
   function store<M, F, S>(client: RedisClientType<M, F, S>, value: string) {
      // use client here...
   } 
   ```
   This gets ugly quickly.

**Comment by leibale** [comment]
regarding 3 - you can use the typescript `typeof` operator
```typescript
const client = createClient({
  // ...
});

type MyRedisClient = typeof client;
```

**Comment by tobiasdiez** [comment]
Yes, but only if you don't use a factory method to create the client, since then `client` is only visible in that factory method and thus its type cannot be exported to other modules (or used to annotate the return type of the factory).

**Comment by thatcort** [comment]
Just came here to say that all of this seems far too hard and worthy of a breaking change to the type definitions. After struggling with this for far too long I just put `const client = redis.createClient(redisClientOptions) as RedisClientType<any, any, any>` in my factory function.

**Comment by spdrman** [comment]
I did this, which worked for me:

`const SendHSetBatch = async <
  M extends RedisModules,
  F extends RedisFunctions,
  S extends RedisScripts
>(
  redisClient: RedisClientType<M, F, S>,
  input: IBatch
) => {}`

**Comment by bowmana** [comment]
This worked for me:
`import  { createClient, RedisClientType, RedisClientOptions } from "redis";
const redisURL = process.env.REDIS_URL || "redis://localhost:6379";
const factory = (options: RedisClientOptions) : RedisClientType => {
    return createClient(options) as RedisClientType;
};
const redisClient: RedisClientType = factory({url: redisURL});
redisClient.on("error", (err) => {
    console.error("Error connecting to Redis:", err);
});

`

**Comment by clemenspeters** [comment]
Thanks @thatcort , I my case just `const client = redis.createClient(redisClientOptions) as RedisClientType` was sufficient already.
